name: build
on:
  workflow_call:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
            ./deployments/k3d/.tmp/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: build
        run: make
      - name: build static x86
        run: make build-cross-x86_64-unknown-linux-gnu
      - name: build static arm
        run: make build-cross-aarch64-unknown-linux-gnu
      - name: build k3d demo
        run: make build-image
        working-directory: ./deployments/k3d
