name: build
on:
  workflow_call:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
            ./deployments/k3d/.tmp/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: build static x86
        run: make build-cross-x86_64-unknown-linux-gnu
      - name: package release assets
        run: |
          mkdir _dist
          cp target/release/containerd-shim-*-v1 _dist/
          cd _dist
          tar czf containerd-wasm-shims-v1.tar.gz containerd-shim-*-v1
      - uses: actions/upload-artifact@v3
        with:
          name: builds.tgz
          path: _dist/containerd-wasm-shims-v1.tar.gz
      - name: build k3d demo
        run: make build-image
        working-directory: ./deployments/k3d
